# encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# Language.destroy_all
# Language.create(name_translations: {"en-US" => "Afrikaans", "it-IT" => "Afrikaans"}, native_name: "Afrikaans", code: "af")
# Language.create(name_translations: {"en-US" => "Arabic", "it-IT" => "Arabo"}, native_name: "العربية", code: "ar")
# Language.create(name_translations: {"en-US" => "Albanian", "it-IT" => "Albanese"}, native_name: "Shqip", code: "sq")
# Language.create(name_translations: {"en-US" => "Basque", "it-IT" => "Basco"}, native_name: "Euskera", code: "eu")
# Language.create(name_translations: {"en-US" => "Belarusian", "it-IT" => "Bielorusso"}, native_name: "Беларуская", code: "be")
# Language.create(name_translations: {"en-US" => "Bengali", "it-IT" => "Bengalese"}, native_name: "বাংলা", code: "bn")
# Language.create(name_translations: {"en-US" => "Bulgarian", "it-IT" => "Bulgaro"}, native_name: "Български", code: "bg")
# Language.create(name_translations: {"en-US" => "Catalan", "it-IT" => "Catalano"}, native_name: "Català", code: "ca")
# Language.create(name_translations: {"en-US" => "Chinese (Mandarin)", "it-IT" => "Cinese (Mandarino)"}, native_name: "官话", code: "zh-guoyu")
# Language.create(name_translations: {"en-US" => "Chinese (Cantonese)", "it-IT" => "Cinese (Cantonese)"}, native_name: "粤语", code: "zh-yue")
# Language.create(name_translations: {"en-US" => "Croatian", "it-IT" => "Croato"}, native_name: "Hrvatski", code: "hr")
# Language.create(name_translations: {"en-US" => "Czech", "it-IT" => "Ceco"}, native_name: "Čeština", code: "cs")
# Language.create(name_translations: {"en-US" => "Danish", "it-IT" => "Danese"}, native_name: "Dansk", code: "da")
# Language.create(name_translations: {"en-US" => "Dutch", "it-IT" => "Olandese"}, native_name: "Nederlands", code: "nl")
# Language.create(name_translations: {"en-US" => "English", "it-IT" => "Inglese"}, native_name: "English", code: "en")
# Language.create(name_translations: {"en-US" => "Estonian", "it-IT" => "Estone"}, native_name: "Eesti", code: " et")
# Language.create(name_translations: {"en-US" => "Finnish", "it-IT" => "Finlandese"}, native_name: "Suomi", code: "fi")
# Language.create(name_translations: {"en-US" => "French", "it-IT" => "Francese"}, native_name: "Français", code: "fr")
# Language.create(name_translations: {"en-US" => "Galician", "it-IT" => "Gallego"}, native_name: "Galego", code: "gl")
# Language.create(name_translations: {"en-US" => "German", "it-IT" => "Tedesco"}, native_name: "Deutsch", code: "de")
# Language.create(name_translations: {"en-US" => "Greek", "it-IT" => "Greco"}, native_name: "Ελληνικά", code: "el")
# Language.create(name_translations: {"en-US" => "Hindi", "it-IT" => "Hindi"}, native_name: "हिंदी", code: "hi")
# Language.create(name_translations: {"en-US" => "Hungarian", "it-IT" => "Ungherese"}, native_name: "Magyar", code: "hu")
# Language.create(name_translations: {"en-US" => "Icelandic", "it-IT" => "Islandese"}, native_name: "Íslenska", code: "is")
# Language.create(name_translations: {"en-US" => "Indonesian", "it-IT" => "Indonesiano"}, native_name: "Bahasa Indonesia", code: "id")
# Language.create(name_translations: {"en-US" => "Irish", "it-IT" => "Gaelico"}, native_name: "Gaeilge", code: "ga")
# Language.create(name_translations: {"en-US" => "Italian", "it-IT" => "Italiano"}, native_name: "Italiano", code: "it")
# Language.create(name_translations: {"en-US" => "Japanese", "it-IT" => "Giapponese"}, native_name: "日本語", code: "ja")
# Language.create(name_translations: {"en-US" => "Korean", "it-IT" => "Coreano"}, native_name: "한국어", code: "ko")
# Language.create(name_translations: {"en-US" => "Macedonian", "it-IT" => "Macedone"}, native_name: "Македонски", code: "mk")
# Language.create(name_translations: {"en-US" => "Malaysian", "it-IT" => "Malesiano"}, native_name: "Bahasa Melayu", code: "ms")
# Language.create(name_translations: {"en-US" => "Norwegian", "it-IT" => "Norvegese"}, native_name: "Norsk", code: "no")
# Language.create(name_translations: {"en-US" => "Polish", "it-IT" => "Polacco"}, native_name: "Polski", code: "pl")
# Language.create(name_translations: {"en-US" => "Portuguese", "it-IT" => "Portoghese"}, native_name: "Português", code: "pt")
# Language.create(name_translations: {"en-US" => "Romanian", "it-IT" => "Rumeno"}, native_name: "Română", code: "ro")
# Language.create(name_translations: {"en-US" => "Russian", "it-IT" => "Russo"}, native_name: "Pyccĸий", code: "ru")
# Language.create(name_translations: {"en-US" => "Serbian", "it-IT" => "Serbo"}, native_name: "Srpski", code: "sr")
# Language.create(name_translations: {"en-US" => "Slovak", "it-IT" => "Slovacco"}, native_name: "Slovenčina", code: "sk")
# Language.create(name_translations: {"en-US" => "Slovenian", "it-IT" => "Sloveno"}, native_name: "Slovenščina", code: "sl")
# Language.create(name_translations: {"en-US" => "Spanish", "it-IT" => "Spagnolo"}, native_name: "Español", code: "es")
# Language.create(name_translations: {"en-US" => "Swedish", "it-IT" => "Svedese"}, native_name: "Svenska", code: "sv")
# Language.create(name_translations: {"en-US" => "Turkish", "it-IT" => "Turco"}, native_name: "Tϋrkçe", code: "tr")
# Language.create(name_translations: {"en-US" => "Ukranian", "it-IT" => "Ucraino"}, native_name: "Українська", code: "uk")

# http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
# tab = $("table.wikitable.sortable.jquery-tablesorter").find("tbody")[0]; for (row in tab.rows) { console.log('Country.create(name_translations: { "en-US" => "' + tab.rows[row].cells[1].textContent +'" }, code: "' + tab.rows[row].cells[0].textContent + '")'); }
# Country.destroy_all
# Country.create(name_translations: { "en-US" => "Andorra" }, code: "AD")
# Country.create(name_translations: { "en-US" => "United Arab Emirates" }, code: "AE")
# Country.create(name_translations: { "en-US" => "Afghanistan" }, code: "AF")
# Country.create(name_translations: { "en-US" => "Antigua and Barbuda" }, code: "AG")
# Country.create(name_translations: { "en-US" => "Anguilla" }, code: "AI")
# Country.create(name_translations: { "en-US" => "Albania" }, code: "AL")
# Country.create(name_translations: { "en-US" => "Armenia" }, code: "AM")
# Country.create(name_translations: { "en-US" => "Angola" }, code: "AO")
# Country.create(name_translations: { "en-US" => "Antarctica" }, code: "AQ")
# Country.create(name_translations: { "en-US" => "Argentina" }, code: "AR")
# Country.create(name_translations: { "en-US" => "American Samoa" }, code: "AS")
# Country.create(name_translations: { "en-US" => "Austria" }, code: "AT")
# Country.create(name_translations: { "en-US" => "Australia" }, code: "AU")
# Country.create(name_translations: { "en-US" => "Aruba" }, code: "AW")
# Country.create(name_translations: { "en-US" => "Aland Islands" }, code: "AX")
# Country.create(name_translations: { "en-US" => "Azerbaijan" }, code: "AZ")
# Country.create(name_translations: { "en-US" => "Bosnia and Herzegovina" }, code: "BA")
# Country.create(name_translations: { "en-US" => "Barbados" }, code: "BB")
# Country.create(name_translations: { "en-US" => "Bangladesh" }, code: "BD")
# Country.create(name_translations: { "en-US" => "Belgium" }, code: "BE")
# Country.create(name_translations: { "en-US" => "Burkina Faso" }, code: "BF")
# Country.create(name_translations: { "en-US" => "Bulgaria" }, code: "BG")
# Country.create(name_translations: { "en-US" => "Bahrain" }, code: "BH")
# Country.create(name_translations: { "en-US" => "Burundi" }, code: "BI")
# Country.create(name_translations: { "en-US" => "Benin" }, code: "BJ")
# Country.create(name_translations: { "en-US" => "Saint Barthélemy" }, code: "BL")
# Country.create(name_translations: { "en-US" => "Bermuda" }, code: "BM")
# Country.create(name_translations: { "en-US" => "Brunei Darussalam" }, code: "BN")
# Country.create(name_translations: { "en-US" => "Bolivia, Plurinational State of" }, code: "BO")
# Country.create(name_translations: { "en-US" => "Bonaire, Sint Eustatius and Saba" }, code: "BQ")
# Country.create(name_translations: { "en-US" => "Brazil" }, code: "BR")
# Country.create(name_translations: { "en-US" => "Bahamas" }, code: "BS")
# Country.create(name_translations: { "en-US" => "Bhutan" }, code: "BT")
# Country.create(name_translations: { "en-US" => "Bouvet Island" }, code: "BV")
# Country.create(name_translations: { "en-US" => "Botswana" }, code: "BW")
# Country.create(name_translations: { "en-US" => "Belarus" }, code: "BY")
# Country.create(name_translations: { "en-US" => "Belize" }, code: "BZ")
# Country.create(name_translations: { "en-US" => "Canada" }, code: "CA")
# Country.create(name_translations: { "en-US" => "Cocos (Keeling) Islands" }, code: "CC")
# Country.create(name_translations: { "en-US" => "Congo, the Democratic Republic of the" }, code: "CD")
# Country.create(name_translations: { "en-US" => "Central African Republic" }, code: "CF")
# Country.create(name_translations: { "en-US" => "Congo" }, code: "CG")
# Country.create(name_translations: { "en-US" => "Switzerland" }, code: "CH")
# Country.create(name_translations: { "en-US" => "Cote d'Ivoire" }, code: "CI")
# Country.create(name_translations: { "en-US" => "Cook Islands" }, code: "CK")
# Country.create(name_translations: { "en-US" => "Chile" }, code: "CL")
# Country.create(name_translations: { "en-US" => "Cameroon" }, code: "CM")
# Country.create(name_translations: { "en-US" => "China" }, code: "CN")
# Country.create(name_translations: { "en-US" => "Colombia" }, code: "CO")
# Country.create(name_translations: { "en-US" => "Costa Rica" }, code: "CR")
# Country.create(name_translations: { "en-US" => "Cuba" }, code: "CU")
# Country.create(name_translations: { "en-US" => "Cape Verde" }, code: "CV")
# Country.create(name_translations: { "en-US" => "Curaçao" }, code: "CW")
# Country.create(name_translations: { "en-US" => "Christmas Island" }, code: "CX")
# Country.create(name_translations: { "en-US" => "Cyprus" }, code: "CY")
# Country.create(name_translations: { "en-US" => "Czech Republic" }, code: "CZ")
# Country.create(name_translations: { "en-US" => "Germany" }, code: "DE")
# Country.create(name_translations: { "en-US" => "Djibouti" }, code: "DJ")
# Country.create(name_translations: { "en-US" => "Denmark" }, code: "DK")
# Country.create(name_translations: { "en-US" => "Dominica" }, code: "DM")
# Country.create(name_translations: { "en-US" => "Dominican Republic" }, code: "DO")
# Country.create(name_translations: { "en-US" => "Algeria" }, code: "DZ")
# Country.create(name_translations: { "en-US" => "Ecuador" }, code: "EC")
# Country.create(name_translations: { "en-US" => "Estonia" }, code: "EE")
# Country.create(name_translations: { "en-US" => "Egypt" }, code: "EG")
# Country.create(name_translations: { "en-US" => "Western Sahara" }, code: "EH")
# Country.create(name_translations: { "en-US" => "Eritrea" }, code: "ER")
# Country.create(name_translations: { "en-US" => "Spain" }, code: "ES")
# Country.create(name_translations: { "en-US" => "Ethiopia" }, code: "ET")
# Country.create(name_translations: { "en-US" => "Finland" }, code: "FI")
# Country.create(name_translations: { "en-US" => "Fiji" }, code: "FJ")
# Country.create(name_translations: { "en-US" => "Falkland Islands (Malvinas)" }, code: "FK")
# Country.create(name_translations: { "en-US" => "Micronesia, Federated States of" }, code: "FM")
# Country.create(name_translations: { "en-US" => "Faroe Islands" }, code: "FO")
# Country.create(name_translations: { "en-US" => "France" }, code: "FR")
# Country.create(name_translations: { "en-US" => "Gabon" }, code: "GA")
# Country.create(name_translations: { "en-US" => "United Kingdom" }, code: "GB")
# Country.create(name_translations: { "en-US" => "Grenada" }, code: "GD")
# Country.create(name_translations: { "en-US" => "Georgia" }, code: "GE")
# Country.create(name_translations: { "en-US" => "French Guiana" }, code: "GF")
# Country.create(name_translations: { "en-US" => "Guernsey" }, code: "GG")
# Country.create(name_translations: { "en-US" => "Ghana" }, code: "GH")
# Country.create(name_translations: { "en-US" => "Gibraltar" }, code: "GI")
# Country.create(name_translations: { "en-US" => "Greenland" }, code: "GL")
# Country.create(name_translations: { "en-US" => "Gambia" }, code: "GM")
# Country.create(name_translations: { "en-US" => "Guinea" }, code: "GN")
# Country.create(name_translations: { "en-US" => "Guadeloupe" }, code: "GP")
# Country.create(name_translations: { "en-US" => "Equatorial Guinea" }, code: "GQ")
# Country.create(name_translations: { "en-US" => "Greece" }, code: "GR")
# Country.create(name_translations: { "en-US" => "South Georgia and the South Sandwich Islands" }, code: "GS")
# Country.create(name_translations: { "en-US" => "Guatemala" }, code: "GT")
# Country.create(name_translations: { "en-US" => "Guam" }, code: "GU")
# Country.create(name_translations: { "en-US" => "Guinea-Bissau" }, code: "GW")
# Country.create(name_translations: { "en-US" => "Guyana" }, code: "GY")
# Country.create(name_translations: { "en-US" => "Hong Kong" }, code: "HK")
# Country.create(name_translations: { "en-US" => "Heard Island and McDonald Islands" }, code: "HM")
# Country.create(name_translations: { "en-US" => "Honduras" }, code: "HN")
# Country.create(name_translations: { "en-US" => "Croatia" }, code: "HR")
# Country.create(name_translations: { "en-US" => "Haiti" }, code: "HT")
# Country.create(name_translations: { "en-US" => "Hungary" }, code: "HU")
# Country.create(name_translations: { "en-US" => "Indonesia" }, code: "ID")
# Country.create(name_translations: { "en-US" => "Ireland" }, code: "IE")
# Country.create(name_translations: { "en-US" => "Israel" }, code: "IL")
# Country.create(name_translations: { "en-US" => "Isle of Man" }, code: "IM")
# Country.create(name_translations: { "en-US" => "India" }, code: "IN")
# Country.create(name_translations: { "en-US" => "British Indian Ocean Territory" }, code: "IO")
# Country.create(name_translations: { "en-US" => "Iraq" }, code: "IQ")
# Country.create(name_translations: { "en-US" => "Iran, Islamic Republic of" }, code: "IR")
# Country.create(name_translations: { "en-US" => "Iceland" }, code: "IS")
# Country.create(name_translations: { "en-US" => "Italy" }, code: "IT")
# Country.create(name_translations: { "en-US" => "Jersey" }, code: "JE")
# Country.create(name_translations: { "en-US" => "Jamaica" }, code: "JM")
# Country.create(name_translations: { "en-US" => "Jordan" }, code: "JO")
# Country.create(name_translations: { "en-US" => "Japan" }, code: "JP")
# Country.create(name_translations: { "en-US" => "Kenya" }, code: "KE")
# Country.create(name_translations: { "en-US" => "Kyrgyzstan" }, code: "KG")
# Country.create(name_translations: { "en-US" => "Cambodia" }, code: "KH")
# Country.create(name_translations: { "en-US" => "Kiribati" }, code: "KI")
# Country.create(name_translations: { "en-US" => "Comoros" }, code: "KM")
# Country.create(name_translations: { "en-US" => "Saint Kitts and Nevis" }, code: "KN")
# Country.create(name_translations: { "en-US" => "Korea, Democratic People's Republic of" }, code: "KP")
# Country.create(name_translations: { "en-US" => "Korea, Republic of" }, code: "KR")
# Country.create(name_translations: { "en-US" => "Kuwait" }, code: "KW")
# Country.create(name_translations: { "en-US" => "Cayman Islands" }, code: "KY")
# Country.create(name_translations: { "en-US" => "Kazakhstan" }, code: "KZ")
# Country.create(name_translations: { "en-US" => "Lao People's Democratic Republic" }, code: "LA")
# Country.create(name_translations: { "en-US" => "Lebanon" }, code: "LB")
# Country.create(name_translations: { "en-US" => "Saint Lucia" }, code: "LC")
# Country.create(name_translations: { "en-US" => "Liechtenstein" }, code: "LI")
# Country.create(name_translations: { "en-US" => "Sri Lanka" }, code: "LK")
# Country.create(name_translations: { "en-US" => "Liberia" }, code: "LR")
# Country.create(name_translations: { "en-US" => "Lesotho" }, code: "LS")
# Country.create(name_translations: { "en-US" => "Lithuania" }, code: "LT")
# Country.create(name_translations: { "en-US" => "Luxembourg" }, code: "LU")
# Country.create(name_translations: { "en-US" => "Latvia" }, code: "LV")
# Country.create(name_translations: { "en-US" => "Libya" }, code: "LY")
# Country.create(name_translations: { "en-US" => "Morocco" }, code: "MA")
# Country.create(name_translations: { "en-US" => "Monaco" }, code: "MC")
# Country.create(name_translations: { "en-US" => "Moldova, Republic of" }, code: "MD")
# Country.create(name_translations: { "en-US" => "Montenegro" }, code: "ME")
# Country.create(name_translations: { "en-US" => "Saint Martin (French part)" }, code: "MF")
# Country.create(name_translations: { "en-US" => "Madagascar" }, code: "MG")
# Country.create(name_translations: { "en-US" => "Marshall Islands" }, code: "MH")
# Country.create(name_translations: { "en-US" => "Macedonia, the former Yugoslav Republic of" }, code: "MK")
# Country.create(name_translations: { "en-US" => "Mali" }, code: "ML")
# Country.create(name_translations: { "en-US" => "Myanmar" }, code: "MM")
# Country.create(name_translations: { "en-US" => "Mongolia" }, code: "MN")
# Country.create(name_translations: { "en-US" => "Macao" }, code: "MO")
# Country.create(name_translations: { "en-US" => "Northern Mariana Islands" }, code: "MP")
# Country.create(name_translations: { "en-US" => "Martinique" }, code: "MQ")
# Country.create(name_translations: { "en-US" => "Mauritania" }, code: "MR")
# Country.create(name_translations: { "en-US" => "Montserrat" }, code: "MS")
# Country.create(name_translations: { "en-US" => "Malta" }, code: "MT")
# Country.create(name_translations: { "en-US" => "Mauritius" }, code: "MU")
# Country.create(name_translations: { "en-US" => "Maldives" }, code: "MV")
# Country.create(name_translations: { "en-US" => "Malawi" }, code: "MW")
# Country.create(name_translations: { "en-US" => "Mexico" }, code: "MX")
# Country.create(name_translations: { "en-US" => "Malaysia" }, code: "MY")
# Country.create(name_translations: { "en-US" => "Mozambique" }, code: "MZ")
# Country.create(name_translations: { "en-US" => "Namibia" }, code: "NA")
# Country.create(name_translations: { "en-US" => "New Caledonia" }, code: "NC")
# Country.create(name_translations: { "en-US" => "Niger" }, code: "NE")
# Country.create(name_translations: { "en-US" => "Norfolk Island" }, code: "NF")
# Country.create(name_translations: { "en-US" => "Nigeria" }, code: "NG")
# Country.create(name_translations: { "en-US" => "Nicaragua" }, code: "NI")
# Country.create(name_translations: { "en-US" => "Netherlands" }, code: "NL")
# Country.create(name_translations: { "en-US" => "Norway" }, code: "NO")
# Country.create(name_translations: { "en-US" => "Nepal" }, code: "NP")
# Country.create(name_translations: { "en-US" => "Nauru" }, code: "NR")
# Country.create(name_translations: { "en-US" => "Niue" }, code: "NU")
# Country.create(name_translations: { "en-US" => "New Zealand" }, code: "NZ")
# Country.create(name_translations: { "en-US" => "Oman" }, code: "OM")
# Country.create(name_translations: { "en-US" => "Panama" }, code: "PA")
# Country.create(name_translations: { "en-US" => "Peru" }, code: "PE")
# Country.create(name_translations: { "en-US" => "French Polynesia" }, code: "PF")
# Country.create(name_translations: { "en-US" => "Papua New Guinea" }, code: "PG")
# Country.create(name_translations: { "en-US" => "Philippines" }, code: "PH")
# Country.create(name_translations: { "en-US" => "Pakistan" }, code: "PK")
# Country.create(name_translations: { "en-US" => "Poland" }, code: "PL")
# Country.create(name_translations: { "en-US" => "Saint Pierre and Miquelon" }, code: "PM")
# Country.create(name_translations: { "en-US" => "Pitcairn" }, code: "PN")
# Country.create(name_translations: { "en-US" => "Puerto Rico" }, code: "PR")
# Country.create(name_translations: { "en-US" => "Palestinian Territory, Occupied" }, code: "PS")
# Country.create(name_translations: { "en-US" => "Portugal" }, code: "PT")
# Country.create(name_translations: { "en-US" => "Palau" }, code: "PW")
# Country.create(name_translations: { "en-US" => "Paraguay" }, code: "PY")
# Country.create(name_translations: { "en-US" => "Qatar" }, code: "QA")
# Country.create(name_translations: { "en-US" => "Reunion" }, code: "RE")
# Country.create(name_translations: { "en-US" => "Romania" }, code: "RO")
# Country.create(name_translations: { "en-US" => "Serbia" }, code: "RS")
# Country.create(name_translations: { "en-US" => "Russian Federation" }, code: "RU")
# Country.create(name_translations: { "en-US" => "Rwanda" }, code: "RW")
# Country.create(name_translations: { "en-US" => "Saudi Arabia" }, code: "SA")
# Country.create(name_translations: { "en-US" => "Solomon Islands" }, code: "SB")
# Country.create(name_translations: { "en-US" => "Seychelles" }, code: "SC")
# Country.create(name_translations: { "en-US" => "Sudan" }, code: "SD")
# Country.create(name_translations: { "en-US" => "Sweden" }, code: "SE")
# Country.create(name_translations: { "en-US" => "Singapore" }, code: "SG")
# Country.create(name_translations: { "en-US" => "Saint Helena, Ascension and Tristan da Cunha" }, code: "SH")
# Country.create(name_translations: { "en-US" => "Slovenia" }, code: "SI")
# Country.create(name_translations: { "en-US" => "Svalbard and Jan Mayen" }, code: "SJ")
# Country.create(name_translations: { "en-US" => "Slovakia" }, code: "SK")
# Country.create(name_translations: { "en-US" => "Sierra Leone" }, code: "SL")
# Country.create(name_translations: { "en-US" => "San Marino" }, code: "SM")
# Country.create(name_translations: { "en-US" => "Senegal" }, code: "SN")
# Country.create(name_translations: { "en-US" => "Somalia" }, code: "SO")
# Country.create(name_translations: { "en-US" => "Suriname" }, code: "SR")
# Country.create(name_translations: { "en-US" => "South Sudan" }, code: "SS")
# Country.create(name_translations: { "en-US" => "Sao Tome and Principe" }, code: "ST")
# Country.create(name_translations: { "en-US" => "El Salvador" }, code: "SV")
# Country.create(name_translations: { "en-US" => "Sint Maarten (Dutch part)" }, code: "SX")
# Country.create(name_translations: { "en-US" => "Syrian Arab Republic" }, code: "SY")
# Country.create(name_translations: { "en-US" => "Swaziland" }, code: "SZ")
# Country.create(name_translations: { "en-US" => "Turks and Caicos Islands" }, code: "TC")
# Country.create(name_translations: { "en-US" => "Chad" }, code: "TD")
# Country.create(name_translations: { "en-US" => "French Southern Territories" }, code: "TF")
# Country.create(name_translations: { "en-US" => "Togo" }, code: "TG")
# Country.create(name_translations: { "en-US" => "Thailand" }, code: "TH")
# Country.create(name_translations: { "en-US" => "Tajikistan" }, code: "TJ")
# Country.create(name_translations: { "en-US" => "Tokelau" }, code: "TK")
# Country.create(name_translations: { "en-US" => "Timor-Leste" }, code: "TL")
# Country.create(name_translations: { "en-US" => "Turkmenistan" }, code: "TM")
# Country.create(name_translations: { "en-US" => "Tunisia" }, code: "TN")
# Country.create(name_translations: { "en-US" => "Tonga" }, code: "TO")
# Country.create(name_translations: { "en-US" => "Turkey" }, code: "TR")
# Country.create(name_translations: { "en-US" => "Trinidad and Tobago" }, code: "TT")
# Country.create(name_translations: { "en-US" => "Tuvalu" }, code: "TV")
# Country.create(name_translations: { "en-US" => "Taiwan, Province of China" }, code: "TW")
# Country.create(name_translations: { "en-US" => "Tanzania, United Republic of" }, code: "TZ")
# Country.create(name_translations: { "en-US" => "Ukraine" }, code: "UA")
# Country.create(name_translations: { "en-US" => "Uganda" }, code: "UG")
# Country.create(name_translations: { "en-US" => "United States Minor Outlying Islands" }, code: "UM")
# Country.create(name_translations: { "en-US" => "United States" }, code: "US")
# Country.create(name_translations: { "en-US" => "Uruguay" }, code: "UY")
# Country.create(name_translations: { "en-US" => "Uzbekistan" }, code: "UZ")
# Country.create(name_translations: { "en-US" => "Holy See (Vatican City State)" }, code: "VA")
# Country.create(name_translations: { "en-US" => "Saint Vincent and the Grenadines" }, code: "VC")
# Country.create(name_translations: { "en-US" => "Venezuela, Bolivarian Republic of" }, code: "VE")
# Country.create(name_translations: { "en-US" => "Virgin Islands, British" }, code: "VG")
# Country.create(name_translations: { "en-US" => "Virgin Islands, U.S." }, code: "VI")
# Country.create(name_translations: { "en-US" => "Viet Nam" }, code: "VN")
# Country.create(name_translations: { "en-US" => "Vanuatu" }, code: "VU")
# Country.create(name_translations: { "en-US" => "Wallis and Futuna" }, code: "WF")
# Country.create(name_translations: { "en-US" => "Samoa" }, code: "WS")
# Country.create(name_translations: { "en-US" => "Yemen" }, code: "YE")
# Country.create(name_translations: { "en-US" => "Mayotte" }, code: "YT")
# Country.create(name_translations: { "en-US" => "South Africa" }, code: "ZA")
# Country.create(name_translations: { "en-US" => "Zambia" }, code: "ZM")
# Country.create(name_translations: { "en-US" => "Zimbabwe" }, code: "ZW")
